apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: registry.cloud.okteto.net/manusiaiseng/strapi:dev
        name: backend

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: LoadBalancer  
  ports:
  - name: "backend"
    port: 443
  selector:
    app: backend
